language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
install: yarn
script: yarn build
before_deploy: rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: N4QAOC9WceaXOouNMW0YotBBz5y49UIOGF5L9fJ5WaWtAFvFhPlFQ6CmN0vSjXqnpv/Go8hWuabHSQc6yYk/FmsA2hHTSejhKv5NVpXza6QA5DrOgdfaHsYpvMCGrm/NQvUhcF4ouTS7wRy+rSmFmkSfbgUj8Mcu/QGxTACKSJctGq4M6BIQWpnoZlK57RoCu8YcWOAbMcJ+9ENgqfjzQaSBtCZXbIwWDto50ISEE2Y56cTEp1Zeij32KqYeF32v6ddbMQ4Q9a2gBxKizYY/fh5TELdImatnRn8HIDwxX8mMU5LySUuIGIeMbRkKAOQ0fhul2wpOOslTQpeEZpCs05sTNTNanhDN3jz9BgqIEzcsaQPihWqSMsKt35nA7lXrHfz4YroyV4pEAbD6OfoQucl+4S8H/muBetGHMQm2wRDvwJtMM0Lnyk0paiqFD41YoG4AZmPTCHFTjGEbtgYxadk/NVV26wuO+wYUI0A7cqs6ZW2IiOMldXI8RMZhuV78aiCfv0KleenCm2F4Hg0u5IaZmrgPSCJIRW+GFQm2rlnxOcYl29H+6sPUChaWIvj9PUh5X94JmcP3eEj5NJnHRtUTu54f6p4jujRIyHJQ/y5Sn7QGtl1hw+gYrOCExGu2fRDepdconZIJfQlF4gHyknbsmGfoETCxD9cHP5vOb+w=
  app:
    master: hoodie-notes
